### ISSUE TITLE
Remove the workaround for the boolean Jinja comparison issue

### ISSUE THREAD

**Issue by spetrosi** [linux-system-roles/mssql#13]
I introduced the following workaround because the CI tests used older Jinja version and hence the comparison of two boolean vars was failing because of the issue https://github.com/pallets/jinja/issues/813
When a newer Jinja is added to the CI, the workaround can be removed and the following single task can be used:
```
    - name: Verify the traceflag setting
      assert:
        that: >-
          ('3979' in __mssql_conf_get_traceflag.stdout) ==
          __verify_mssql_is_tuned_for_fua
```

**Comment by spetrosi** [comment]
Problematic lines in tests/tasks/verify_settings.yml
```
    - name: Verify the traceflag setting
      assert:
        that: "'3979' in __mssql_conf_get_traceflag.stdout"
      when: __verify_mssql_is_tuned_for_fua

    - name: Verify the traceflag setting
      assert:
        that: "'3979' not in __mssql_conf_get_traceflag.stdout"
      when: not __verify_mssql_is_tuned_for_fua
```
