### ISSUE TITLE
Database Error and Server not accessible

### ISSUE THREAD

**Issue by ajith2234** [linux-system-roles/mssql#95]
Hi
I want to use this ansible role to create a three-node SQL cluster with high availability on a centos VM. I am new to ansible and SQL and am facing some issues. I have provided the play.yml file below:
                  
>                   - hosts: all
>                     become: yes
>                     become_user: root 
>                     vars:
>                       mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
>                       mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
>                       mssql_accept_microsoft_sql_server_standard_eula: true
>                       mssql_password: "p@55w0rD"
>                       mssql_edition: Developer
>                       mssql_firewall_configure: true
>                       mssql_enable_sql_agent: true
>                       mssql_ha_configure: true
>                       mssql_ha_firewall_configure: true
>                       mssql_ha_cert_name: dbmCert
>                       mssql_ha_master_key_password: "p@55w0rD1"
>                       mssql_ha_private_key_password: "p@55w0rD2"
>                       mssql_ha_reset_cert: false
>                       mssql_ha_endpoint_name: dbm_Endpoint
>                       mssql_ha_ag_name: AG1
>                       mssql_ha_db_name: testdb
>                       mssql_ha_login: HALogin
>                       mssql_ha_login_password: "p@55w0rD3"
>                       mssql_ha_cluster_run_role: true
>                       ha_cluster_enable_repos: true
>                       ha_cluster_cluster_name: AG1
>                       ha_cluster_hacluster_password: "p@55w0rD4"
>                       ha_cluster_cluster_properties:
>                         - attrs:
>                           - name: cluster-recheck-interval
>                             value: 2min
>                           - name: start-failure-is-fatal
>                             value: true
>                           - name: stonith-enabled
>                             value: true
>                       ha_cluster_resource_primitives:
>                         - id: ag_cluster
>                           agent: ocf:mssql:ag
>                           instance_attrs:
>                             - attrs:
>                               - name: ag_name
>                                 value: AG1
>                           meta_attrs:
>                             - attrs:
>                               - name: failure-timeout
>                                 value: 60s  
>                         - id: virtualip
>                           agent: ocf:heartbeat:IPaddr2
>                           instance_attrs:
>                             - attrs:
>                               - name: ip
>                                 value: 20.XXX.XXX.XX
>                           operations:
>                             - action: monitor
>                               attrs:
>                                 - name: interval
>                                   value: 30s
>                       ha_cluster_resource_clones:
>                         - resource_id: ag_cluster
>                           promotable: yes
>                           meta_attrs:
>                             - attrs:
>                               - name: notify
>                                 value: true
>                       ha_cluster_constraints_colocation:
>                         - resource_leader:
>                             id: ag_cluster-clone
>                             role: Promoted
>                           resource_follower:
>                             id: virtualip
>                           options:
>                             - name: score
>                               value: INFINITY
>                       ha_cluster_constraints_order:
>                         - resource_first:
>                             id: ag_cluster-clone
>                             action: promote
>                           resource_then:
>                             id: virtualip
>                             action: start
>                     roles:
>                       - microsoft.sql.server

   
**1. Issue with the database name**
- There is an error saying that my database name does not exist. I then tried not using the  "mssql_ha_db_name:" variable in the playbook and I got another error saying there was a syntax error in the code.
- I would like to know if creating a database is necessary when configuring high availability. 

 **2. Server not accessible from outside**
- After completion of the ansible code when I am not able to access the cluster from a remote host. I checked if the ports were open and found no issue. I am able to access the server from inside the virtual machine.

 **2. Prerequisites for High Availability**
- I would also like to know if there are configurations we must do in the virtual machines before running this to role for high availability.

Thank you

**Comment by spetrosi** [comment]
Hello, thank you for your feedback. Are you using the role from Ansible Galaxy or you are using this repo's source code?
Note that I am currently doing more improvements to the role, a number of them. I am going to publish a new version with the improvements to Galaxy early this week. If you want to take a look at the new functionality faster, you can use this repo's source code.

> There is an error saying that my database name does not exist. I then tried not using the "mssql_ha_db_name:" variable in the playbook and I got another error saying there was a syntax error in the code.
> I would like to know if creating a database is necessary when configuring high availability.

Yes, you must create a database in SQL Server and provide the name of the existing database with the `mssql_ha_db_name` variable so that the role backs it up and replicates it. One of the recent PRs has added a `mssql_pre_input_sql_file` functionality that simplifies this, see #84. In your playbook, you can run a task to set the `mssql_pre_input_sql_file` fact for the primary node, and with this fact point to an sql script that creates a database. Then, call the role on all hosts to configure for HA.

For example, here the first tasks would use the https://github.com/linux-system-roles/mssql/blob/master/tests/templates/create_example_db.j2 jinja script to generate an sql script to create an Example DB database with sample content:

```
    - name: Set facts to create a test DB on primary as a pre task
      set_fact:
        mssql_pre_input_sql_file: create_example_db.j2
        __mssql_test_db_name: ExampleDB
      when: mssql_ha_replica_type == 'primary'

    - name: Run on all hosts to configure HA cluster
      include_role:
        name: linux-system-roles.mssql
```

This functionality is not present in the role in Galaxy yet.

> After completion of the ansible code when I am not able to access the cluster from a remote host. I checked if the ports were open and found no issue. I am able to access the server from inside the virtual machine.

You can check first if the cluster was set up correctly. Try running `pcs status` and see if all resources are running. Also, if you are running VMs from your laptop, I wonder if you must make some further configuration to expose their apps to the internet externally.

> I would also like to know if there are configurations we must do in the virtual machines before running this to role for high availability.

I have opened #96 to add an explicit prerequisites section to the role. The role itself only requires a database created, and other requirements are from the SQL Server side, so README redirects to Microsoft docs for this.

**Comment by richm** [comment]
> Hi @spetrosi Thank you for answering my question on such short notice. I am indeed using the role from ansible-galaxy. I would like to know how to use the source code instead of using it from ansible-galaxy.

https://galaxy.ansible.com/docs/using/installing.html#role-versions

try something like this:
```
ansible-galaxy role install git+https://github.com/linux-system-roles/mssql.git
```

**Comment by spetrosi** [comment]
Good new @ajith2234, I have published a new version 1. of role to Galaxy today. So you should be able to install a new version with `ansible-galaxy`. The new version is 1.2.1. There are many changes to the README file, so ensure to read it and use the updated examples from it.

**Comment by ajith2234** [comment]
Hi @richm and @spetrosi 
Thank you

**Comment by ajith2234** [comment]
> Hello, thank you for your feedback. Are you using the role from Ansible Galaxy or you are using this repo's source code? Note that I am currently doing more improvements to the role, a number of them. I am going to publish a new version with the improvements to Galaxy early this week. If you want to take a look at the new functionality faster, you can use this repo's source code.
> 
> > There is an error saying that my database name does not exist. I then tried not using the "mssql_ha_db_name:" variable in the playbook and I got another error saying there was a syntax error in the code.
> > I would like to know if creating a database is necessary when configuring high availability.
> 
> Yes, you must create a database in SQL Server and provide the name of the existing database with the `mssql_ha_db_name` variable so that the role backs it up and replicates it. One of the recent PRs has added a `mssql_pre_input_sql_file` functionality that simplifies this, see #84. In your playbook, you can run a task to set the `mssql_pre_input_sql_file` fact for the primary node, and with this fact point to an sql script that creates a database. Then, call the role on all hosts to configure for HA.
> 
> For example, here the first tasks would use the https://github.com/linux-system-roles/mssql/blob/master/tests/templates/create_example_db.j2 jinja script to generate an sql script to create an Example DB database with sample content:
> 
> ```
>     - name: Set facts to create a test DB on primary as a pre task
>       set_fact:
>         mssql_pre_input_sql_file: create_example_db.j2
>         __mssql_test_db_name: ExampleDB
>       when: mssql_ha_replica_type == 'primary'
> 
>     - name: Run on all hosts to configure HA cluster
>       include_role:
>         name: linux-system-roles.mssql
> ```
> 
> This functionality is not present in the role in Galaxy yet.
> 
> > After completion of the ansible code when I am not able to access the cluster from a remote host. I checked if the ports were open and found no issue. I am able to access the server from inside the virtual machine.
> 
> You can check first if the cluster was set up correctly. Try running `pcs status` and see if all resources are running. Also, if you are running VMs from your laptop, I wonder if you must make some further configuration to expose their apps to the internet externally.
> 
> > I would also like to know if there are configurations we must do in the virtual machines before running this to role for high availability.
> 
> I have opened #96 to add an explicit prerequisites section to the role. The role itself only requires a database created, and other requirements are from the SQL Server side, so README redirects to Microsoft docs for this.

Hi 
I tried using the above solution but for some reason it is not working
I have also created a file 'create_example_db.j2' 

play.yml
```
  - hosts: all
    become: yes
    pre_tasks:
      - name: Set facts to create a test DB on primary as a pre task
        set_fact:
          mssql_pre_input_sql_file: create_example_db.j2
          __mssql_test_db_name: ExampleDB
        when: mssql_ha_replica_type == 'primary'
    vars:
      mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
      mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
      mssql_accept_microsoft_sql_server_standard_eula: true
      mssql_password: "ansible123@"
      mssql_edition: Developer
      mssql_manage_firewall: true
      mssql_enable_sql_agent: true
      mssql_ha_configure: true
      mssql_ha_firewall_configure: true
      mssql_ha_listener_port: 5022
      mssql_ha_cert_name: dbCert
      mssql_ha_master_key_password: "p@55w0rD1"
      mssql_ha_private_key_password: "p@55w0rD2"
      mssql_ha_reset_cert: false
      mssql_ha_endpoint_name: db_Endpoint
      mssql_ha_ag_name: AG1
      mssql_ha_db_names: 
        - testdb
      mssql_ha_login: haLogin
      mssql_ha_login_password: "p@55w0rD3"
      mssql_ha_virtual_ip: 10.XX.X.X
      mssql_ha_cluster_run_role: true
      ha_cluster_cluster_name: "{{ mssql_ha_ag_name }}"
      ha_cluster_hacluster_password: "p@55w0rD4"
      ha_cluster_cluster_properties:
        - attrs:
            - name: cluster-recheck-interval
              value: 2min
            - name: stonith-enabled
              value: true
            - name: start-failure-is-fatal
              value: true
      ha_cluster_resource_primitives:
        - id: ag_cluster
          agent: ocf:mssql:ag
          instance_attrs:
            - attrs:
                - name: ag_name
                  value: "{{ mssql_ha_ag_name }}"
          meta_attrs:
            - attrs:
                - name: failure-timeout
                  value: 60s
        - id: virtualip
          agent: ocf:heartbeat:IPaddr2
          instance_attrs:
            - attrs:
                - name: ip
                  value: "{{ mssql_ha_virtual_ip }}"
                - name: cidr_netmask
                  value: 24
          operations:
            - action: monitor
              attrs:
                - name: interval
                  value: 30s
      ha_cluster_resource_clones:
        - resource_id: ag_cluster
          promotable: yes
          meta_attrs:
            - attrs:
                - name: notify
                  value: true
      ha_cluster_constraints_colocation:
        - resource_leader:
            id: ag_cluster-clone
            role: Promoted
          resource_follower:
            id: virtualip
          options:
            - name: score
              value: INFINITY
      ha_cluster_constraints_order:
        - resource_first:
            id: ag_cluster-clone
            action: promote
          resource_then:
            id: virtualip
            action: start
    roles:
      - microsoft.sql.server
```
# ERROR
![image](https://user-images.githubusercontent.com/90108350/187366074-5102fd2a-35ff-4e04-aa7f-3382d6d68cf2.png)

- Is there something which i am doing wrong?
Thank you
